### PR TITLE
Removing NC from CC license

### PR DESCRIPTION
**Pull request by wvangeit**

### CODE REVIEW

**Comment by wvangeit** [comment]
@anilbey i'll still remove the NC from more places. But it seems at the moment the tests are not working?

**Comment by anilbey** [comment]
@wvangeit let me see what is wrong.

**Comment by wvangeit** [comment]
For me this can be merged after the tests run again.

For future reference, sed commands to change the headers:
```
 find ./ -path ./.git -prune -o -name *.py -exec gsed -i 's/Creative Commons Attribution-NonCommercial 4.0 International License/Creative Commons Attribution 4.0 International License/g' {} \;
 find ./ -path ./.git -prune -o -name *.hoc -exec gsed -i 's/Creative Commons Attribution-NonCommercial 4.0 International License/Creative Commons Attribution 4.0 International License/g' {} \;

find ./ -path ./.git -prune -o -name *.py -exec gsed -i 's#/licenses/by-nc/4.0#/licenses/by/4.0#g' {} \;
find ./ -path ./.git -prune -o -name *.hoc -exec gsed -i 's#/licenses/by-nc/4.0#/licenses/by/4.0#g' {} \;
```

**Comment by anilbey** [comment]
https://github.com/BlueBrain/SSCxEModelExamples/pull/23 fixes the CI failures.

**Pull request merged**
